# Generated by Django 4.1.5 on 2023-03-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_class_marks_marktype_person_persontype_studentdata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['id'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['id'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='marktype',
            options={'ordering': ['id'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'ordering': ['id'], 'verbose_name': 'Тип персоны', 'verbose_name_plural': 'Тип персон'},
        ),
        migrations.AlterModelOptions(
            name='studentdata',
            options={'ordering': ['id'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['id'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ['id'], 'verbose_name': 'Семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AlterField(
            model_name='class',
            name='ClassName',
            field=models.CharField(max_length=255, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='class',
            name='StdId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentdata', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Mark',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='MarkType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.marktype', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='PrsnId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.person', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='SubjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subjects', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='marktype',
            name='MarkType',
            field=models.CharField(max_length=255, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='marktype',
            name='TypeName',
            field=models.CharField(max_length=255, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PrsnDOB',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PrsnFristName',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PrsnScndName',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PrsnThrdName',
            field=models.CharField(max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PrsnType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.persontype', verbose_name='Принадлежность'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='Prsntype',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='PrsnId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.person', verbose_name='Персона'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='StdAddress',
            field=models.CharField(max_length=255, verbose_name='Место жительства'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='StdDOB',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='StdJoinDate',
            field=models.DateField(verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='StdName',
            field=models.CharField(max_length=255, verbose_name='Имя студента'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='SubjectName',
            field=models.CharField(max_length=255, verbose_name='Название занятия'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='TermId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.terms', verbose_name='К какому семестру'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='TermName',
            field=models.CharField(max_length=255, verbose_name='Название семестра'),
        ),
    ]
