# Generated by Django 4.1.5 on 2023-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_class_slug_marks_slug_marktype_slug_person_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='Text',
            field=models.TextField(default='gsdf', verbose_name='Описание занятия'),
            preserve_default=False,
        ),
    ]
