# Generated by Django 4.1.5 on 2023-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_subjects_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='Duration',
            field=models.IntegerField(default=2, verbose_name='Время обучения в неделях'),
            preserve_default=False,
        ),
    ]
