# Generated by Django 4.1.5 on 2023-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_class_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='Price',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
